### ISSUE TITLE
Write a Blog/Screncast on Azure functions

### ISSUE THREAD

**Issue by xlight05** [ballerina-platform/module-ballerinax-azure.functions#505]
**Description:**
$Subject

**Describe your task(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by anupama-pathirage** [comment]
@xlight05 Seems the issue is still open, but moved to done in sprint 66 project board. Can we close this issue?

**Comment by xlight05** [comment]
Yes. Blog is published on SO. 

https://stackoverflow.com/collectives/wso2/articles/74323311/building-azure-functions-project-with-ballerina
