### ISSUE TITLE
Results vary when resource function is interchanged

### ISSUE THREAD

**Issue by Thevakumar-Luheerathan** [ballerina-platform/module-ballerinax-azure.functions#540]
**Description:**
```ballerina 
import ballerinax/azure_functions as af;

service / on ep1 {

    resource function get helloquery/alpha() returns string {
        return "Hello from the hello-query--";
    }

    resource function get helloquery/[string alpha]() returns string{
        return "Hello from the hello-query";
    }
}
```
Above one's results (Runtime result)differ from below one.

```ballerina 
import ballerinax/azure_functions as af;

service / on ep1 {

    resource function get helloquery/[string alpha]() returns string{
        return "Hello from the hello-query";
    }
   
    resource function get helloquery/alpha() returns string {
        return "Hello from the hello-query--";
    }
}
```
resource function with path parameter is moved to top
**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by xlight05** [comment]
It seems like this is the way the routing works from azure's side. If there is a path parameter that can be applied for the same path, and it followers the registered order. ;( 

Closing as this is not a bug
